### ISSUE TITLE
nigga

### ISSUE THREAD

**Issue by Saturno10** [SoliderAlejandroESP/maven-test-project#1]
el problema es que eres un nigga

░░░░░░░░░░░░░░░▄▀▄░░░░░░░░░░░░░░░
░░░░░░░░░░░░░▄▀░░░▀▄░░░░░░░░░░░░░
░░░░░░░░░░░▄▀░░░░▄▀█░░░░░░░░░░░░░
░░░░░░░░░▄▀░░░░▄▀░▄▀░▄▀▄░░░░░░░░░
░░░░░░░▄▀░░░░▄▀░▄▀░▄▀░░░▀▄░░░░░░░
░░░░░░░█▀▄░░░░▀█░▄▀░░░░░░░▀▄░░░░░
░░░▄▀▄░▀▄░▀▄░░░░▀░░░░▄█▄░░░░▀▄░░░
░▄▀░░░▀▄░▀▄░▀▄░░░░░▄▀░█░▀▄░░░░▀▄░
░█▀▄░░░░▀▄░█▀░░░░░░░▀█░▀▄░▀▄░▄▀█░
░▀▄░▀▄░░░░▀░░░░▄█▄░░░░▀▄░▀▄░█░▄▀░
░░░▀▄░▀▄░░░░░▄▀░█░▀▄░░░░▀▄░▀█▀░░░
░░░░░▀▄░▀▄░▄▀░▄▀░█▀░░░░▄▀█░░░░░░░
░░░░░░░▀▄░█░▄▀░▄▀░░░░▄▀░▄▀░░░░░░░
░░░░░░░░░▀█▀░▄▀░░░░▄▀░▄▀░░░░░░░░░
░░░░░░░░░░░░░█▀▄░▄▀░▄▀░░░░░░░░░░░
░░░░░░░░░░░░░▀▄░█░▄▀░░░░░░░░░░░░░
░░░░░░░░░░░░░░░▀█▀░░░░░░░░░░░░░░░

**Comment by SoliderAlejandroESP** [comment]
No

**Comment by SoliderAlejandroESP** [comment]
⣿⣟⡿⣟⣿⣻⢿⣻⣟⡿⣟⣿⣻⢿⣻⣟⡿⣟⣿⣻⢿⣻⣟⡿⣟⣿⣻⢿⣻⢿
⣿⣞⡿⣯⣷⢿⣻⣽⡾⣟⣯⣷⢿⣻⣽⡾⣟⣯⣷⢿⣻⣽⡾⣟⣯⣷⢿⣻⣯⢿
⣿⣞⣿⣽⢾⣟⣯⡷⣿⣻⣽⢾⣟⣯⢿⣯⣍⡙⠺⣿⢯⣷⣟⡿⣽⣾⣻⢷⣻⣿
⣿⣞⡿⣞⣯⡿⣞⣿⣳⡿⣽⣻⣾⣯⢿⣞⣿⣽⣦⡀⠉⠛⣾⢿⣽⣞⣿⣻⣽⣾
⣿⣞⣿⣻⣽⣻⢯⣷⡿⠙⠁⠀⠀⢨⣽⣟⣾⣽⢾⡿⣦⡀⠀⠙⣿⣾⣳⢿⣳⣿
⣿⣾⣹⣷⢿⣹⣿⠏⠀⠀⠀⢀⣾⣿⢿⣾⣹⣾⣿⣹⣿⣷⠀ ⠀⠈⣷⣿⢿⣹⣾
⣿⣞⣷⣟⡿⣝⠁⠀⠀⢀⣄⠀⠙⠯⣿⣞⣯⣷⢯⣷⣟⣾⣷⠀⠀ ⠘⣯⣿⢯⣿
⣿⣞⡿⣞⣿⣻⣷⣦⣶⣿⡿⣷⣆⡀⠈⠻⣷⣯⢿⣳⣯⡷⣿⠀⠀ ⠀⣹⣯⣿⢾
⣿⣞⡿⣯⣷⣟⣷⣻⣽⣾⣻⣽⣻⣷⣄⠀⠈⠙⢿⣽⣳⣿⣻⠀⠀⠀ ⢼⣟⣾⢿
⣿⣞⣿⣽⡾⣽⡾⣯⢷⣯⡷⣟⣷⢯⣿⣷⣤⡀⠈⠙⢷⣯⠏⠀⠀⠀⣾⡿⣽⣻
⣿⢾⣽⣞⣿⣝⠛⠃⣄⠉⠙⠻⢽⢿⣞⣷⣻⢿⣦⡀⠀⠁⠀⠀⠀ ⣼⣿⣻⣽⢿
⣿⢯⣷⡿⠚⠉⢰⣤⡿⣷⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀     ⢺⡿⣷⣻⡽⣿
⣿⢯⡇⠁⠀⣸⣿⢯⣿⡽⣯⡿⣿⢷⣶⣤⣤⣤⣤⣤⣶⣾⣦⣀⠀⠀⢽⣿⡽⣿
⣿⣻⢷⣶⣾⣟⣯⣿⣞⣿⣳⡿⣯⡿⣽⢯⡿⣽⣻⣽⣻⢾⡽⣿⣳⣶⡿⣯⢿⣽
⣿⡽⣟⣾⣳⣯⣟⣾⣽⢾⣯⣟⣷⢿⣻⣯⢿⣻⡽⣷⣻⣟⣿⣳⣿⣳⢿⣻⣯⢿
⣿⡽⣿⣽⣳⣯⢿⡾⠽⣟⣾⣽⠾⢟⡿⣞⡿⠯⣿⡽⠷⠻⣾⣻⣾⡽⣟⣷⣻⢿
